server:
  port: 8090
  servlet:
    context-path: /wh
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.65.152:3306/test2?useSSL=false&amp;characterEncoding=utf-8&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.197.128
    port: 6379
#    password: null
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wanghuan.model

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wanghuan: DEBUG
